test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,25 +9,33 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - run: |
-          echo "job1"
+          echo "failure"
+          exit 1
 
   job2:
     runs-on: ubuntu-latest
+    needs: job1
     steps:
       - run: |
-          echo "job2 failure"
-          exit 1
+          echo "job2"
+
+  job3:
+    runs-on: ubuntu-latest
+    needs: job1
+    steps:
+      - run: |
+          echo "job3"
   
   success:
     runs-on: ubuntu-latest
-    needs: [job1, job2]
+    needs: [job2, job3]
     if: success()
     steps:
       - run: echo "success!"
 
   failure:
     runs-on: ubuntu-latest
-    needs: [job1, job2]
+    needs: [job2, job3]
     if: failure()
     steps:
       - run: echo "failure!"
